const assert = require('node:assert/strict')
const crypto = require('node:crypto')
const { pathToFileURL } = require('node:url')
const path = require('node:path')
const [base, modulePath, tlsBase, https] = process.argv.slice(2)
const { Client } = require(modulePath)

async function main() {
  const esm = await import(pathToFileURL(path.join(modulePath, 'index.mjs')))
  assert.equal(esm.Client, Client)
  assert.equal(crypto.randomBytes(8).length, 8)
  await assert.rejects(new Client().request('GET', tlsBase))
  const client = new Client()
  const payload = Buffer.from(Array.from({ length: 256 }, (_, i) => i))
  let response = await client.request('POST', base + '/echo', [], payload)
  assert.equal(response.status, 200)
  assert.deepEqual(response.body, payload)
  const mutable = Buffer.from('original')
  const pending = client.request('POST', base + '/echo', [], mutable)
  mutable.fill(0)
  assert.equal((await pending).body.toString(), 'original')
  assert.deepEqual(response.headers.filter(h => h.name === 'x-duplicate').map(h => h.value.toString()), ['one', 'two'])
  response = await client.request('GET', base + '/headers', [
    { name: 'X-Input', value: Buffer.from('one') },
    { name: 'X-Input', value: Buffer.from('two') },
  ])
  assert.deepEqual(JSON.parse(response.body), ['one', 'two'])
  response = await client.request('GET', base + '/header-names', [
    { name: 'X-Input', value: Buffer.from('one') },
    { name: 'x-InPut', value: Buffer.from('two') },
  ])
  assert.deepEqual(JSON.parse(response.body), ['X-Input', 'X-Input'])
  response = await client.request('GET', base + '/redirect')
  assert.equal(response.url, base + '/cookie')
  assert.equal(response.body.toString(), 'session=works')
  assert.equal((await client.request('GET', base + '/error')).status, 404)
  assert.throws(() => new Client(0), /INVALID_CONFIG/)
  for (const invalid of [-1, NaN, Infinity, 1.5, 2 ** 32]) {
    assert.throws(() => new Client(invalid), /INVALID_CONFIG/)
    assert.throws(() => new Client(30000, invalid), /INVALID_CONFIG/)
  }
  await assert.rejects(client.request('BAD METHOD', base), /INVALID_REQUEST/)
  await assert.rejects(new Client(30).request('GET', base + '/slow'), /TIMEOUT/)
  await assert.rejects(new Client(30000, 1024).request('GET', base + '/large'), /BODY_TOO_LARGE/)
  const responses = await Promise.all(Array.from({ length: 8 }, (_, i) => client.request('POST', base + '/echo', [], Buffer.from([i]))))
  assert.deepEqual(responses.map(r => r.body[0]), [0, 1, 2, 3, 4, 5, 6, 7])
  assert.equal((await client.get(base + '/inspect?existing=1', { params: [['q', 'a b'], ['q', '中文']] })).json().path, '/inspect?existing=1&q=a+b&q=%E4%B8%AD%E6%96%87')
  response = await client.post(base + '/inspect', { json: { word: '中文' } })
  assert.deepEqual(JSON.parse(response.json().body), { word: '中文' })
  assert.equal(response.json().content_type, 'application/json')
  assert.equal((await client.post(base + '/inspect', { json: null })).json().body, 'null')
  assert.equal((await client.post(base + '/inspect', { form: [['q', 'a b'], ['q', '中文']] })).json().body, 'q=a+b&q=%E4%B8%AD%E6%96%87')
  assert.equal((await client.get(base + '/inspect', { basicAuth: ['user', 'pass'] })).json().authorization, 'Basic dXNlcjpwYXNz')
  assert.equal((await client.get(base + '/inspect', { bearerToken: 'token' })).json().authorization, 'Bearer token')
  assert.equal((await client.get(base + '/redirect', { maxRedirects: 0 })).status, 302)
  client.clearCookies()
  assert.equal((await client.get(base + '/cookie')).text(), '')
  assert.equal((await new Client({ cookies: false }).get(base + '/redirect')).text(), '')
  const configured = new Client({ userAgent: 'tlsurl-test', httpVersion: '1.1' })
  assert.equal((await configured.get(base + '/inspect')).json().user_agent, 'tlsurl-test')
  configured.close()
  await assert.rejects(configured.get(base), error => error.code === 'CLOSED')
  await assert.rejects(client.get(base + '/slow', { timeoutMs: 10 }), error => error.code === 'TIMEOUT')
  await assert.rejects(client.post(base, { body: 'x', json: {} }), error => error.code === 'INVALID_REQUEST')
  await assert.rejects(client.get(base, { basicAuth: ['u', 'p'], bearerToken: 't' }), error => error.code === 'INVALID_REQUEST')
  assert.throws(() => new Client({ connectTimeoutMs: 0 }), /INVALID_CONFIG/)
  assert.throws(() => new Client({ unknown: true }), /INVALID_CONFIG/)
  response = await client.get(base + '/error')
  assert.throws(() => response.raiseForStatus(), error => error.code === 'HTTP_STATUS')
  assert.equal((await new Client({ proxy: base }).get('http://not-a-real-host.invalid/inspect')).json().path, 'http://not-a-real-host.invalid/inspect')
  assert.equal((await new Client({ verify: false }).get(tlsBase)).status, 200)
  client.setCookie(base, 'manual=value; Path=/')
  assert.deepEqual(client.cookies(base), [{ name: 'manual', value: 'value' }])
  assert.equal((await client.get(base + '/cookie')).text(), 'manual=value')
  client.setCookie(base, 'manual=gone; Path=/; Max-Age=0')
  assert.deepEqual(client.cookies(base), [])
  client.setCookie(base, 'secure=hidden; Secure; Path=/')
  assert.deepEqual(client.cookies(base), [])
  const parts = (await client.post(base + '/multipart', { multipart: [
    { name: 'field', data: '中文' },
    { name: 'file', data: payload, filename: 'data.bin', contentType: 'application/octet-stream' },
  ] })).json()
  assert.equal(parts[0].name, 'field')
  assert.equal(Buffer.from(parts[0].data, 'base64').toString(), '中文')
  assert.equal(parts[1].filename, 'data.bin')
  assert.deepEqual(Buffer.from(parts[1].data, 'base64'), payload)
  await assert.rejects(client.post(base, { multipart: [], json: {} }), /INVALID_REQUEST/)
  await assert.rejects(client.get(base, { headers: { Authorization: 'custom' }, bearerToken: 'token' }), /INVALID_REQUEST/)
  if (https) assert.equal((await client.request('GET', 'https://example.com')).status, 200)
  console.log('Node integration checks passed')
}

main().catch(error => { console.error(error); process.exitCode = 1 })
