const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const [base, secure, modulePath] = process.argv.slice(2)
const { Client } = require(modulePath)
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms))
async function state(id, predicate) {
  for (let i = 0; i < 100; i++) {
    const value = await (await fetch(base.replace('ws:', 'http:') + '/state?id=' + id)).json()
    if (predicate(value)) return value
    await sleep(20)
  }
  throw new Error(`websocket state did not converge: ${id}`)
}
async function main() {
  const client = new Client({ caPem: fs.readFileSync(path.join(__dirname, 'certs/ca.pem'), 'utf8') })
  client.setCookie(secure.replace('wss:', 'https:'), 'ws_cookie=ok; Secure; Path=/')
  const socket = await client.websocket(secure + '/headers?id=node-wss', { protocols: ['echo'], headers: { 'X-Test': 'yes' } })
  assert.equal(socket.protocol, 'echo')
  const headers = JSON.parse((await socket.recv()).data.toString())
  assert.equal(headers['x-test'], 'yes')
  assert.equal(headers.cookie, 'ws_cookie=ok')
  const waiting = socket.recv()
  await socket.send('你好')
  const text = await waiting
  assert.equal(text.kind, 'text')
  assert.equal(text.data.toString(), '你好')
  const mutable = Buffer.from(Array.from({length: 256}, (_, i) => i))
  const original = Buffer.from(mutable)
  const sending = socket.send(mutable)
  mutable.fill(0)
  await sending
  assert.deepEqual((await socket.recv()).data, original)
  await socket.ping('hello')
  const pong = await socket.recv()
  assert.equal(pong.kind, 'pong')
  assert.equal(pong.data.toString(), 'hello')
  await socket.send('server-ping')
  assert.equal((await socket.recv()).kind, 'ping')
  await state('node-wss', s => s?.pongs === 1)
  await socket.send('fragment')
  assert.equal((await socket.recv()).data.toString(), 'firstsecond')
  await assert.rejects(socket.close(1005), { code: 'INVALID_REQUEST' })
  await assert.rejects(socket.ping(Buffer.alloc(126)), { code: 'INVALID_REQUEST' })
  const reading = socket.recv()
  // Attach the rejection handler before initiating close to avoid unhandled rejection timing.
  const interrupted = assert.rejects(reading, { code: 'CLOSED' })
  await socket.close(4000, 'done')
  await interrupted
  assert.equal((await state('node-wss', s => s?.closed && s.code !== null)).code, 4000)
  await socket.close()
  await assert.rejects(socket.send('late'), { code: 'CLOSED' })
  const remote = await client.websocket(base + '/echo?id=node-remote')
  await remote.send('server-close')
  const close = await remote.recv()
  assert.equal(close.kind, 'close')
  assert.equal(close.code, 4001)
  assert.equal(close.data.toString(), 'bye')
  await state('node-remote', s => s?.closed)
  const iterator = await client.websocket(base + '/echo?id=node-iterator')
  await iterator.send('one')
  for await (const message of iterator) { assert.equal(message.data.toString(), 'one'); break }
  await state('node-iterator', s => s?.closed)
  const limited = await client.websocket(base + '/echo?id=node-limit', { maxMessageBytes: 1024 })
  await limited.send('large')
  await assert.rejects(limited.recv())
  await state('node-limit', s => s?.closed)
  const timeout = await client.websocket(base + '/echo?id=node-timeout', { operationTimeoutMs: 100 })
  await assert.rejects(timeout.recv(), { code: 'TIMEOUT' })
  await state('node-timeout', s => s?.closed)
  const controller = new AbortController()
  const aborting = await client.websocket(base + '/echo?id=node-abort', { signal: controller.signal })
  const pending = aborting.recv()
  controller.abort()
  await assert.rejects(pending, { code: 'CANCELLED' })
  await state('node-abort', s => s?.closed)
  const handshake = new AbortController()
  const connecting = client.websocket(base + '/hang?id=node-handshake', { signal: handshake.signal })
  await state('node-handshake', s => s !== null)
  handshake.abort()
  await assert.rejects(connecting, { code: 'CANCELLED' })
  await state('node-handshake', s => s?.closed)
  await assert.rejects(client.websocket(base + '/hang?id=node-connect-timeout', { timeoutMs: 100 }), { code: 'TIMEOUT' })
  await assert.rejects(client.websocket(base + '/echo', { protocols: ['invalid,token'] }), { code: 'INVALID_REQUEST' })
  await assert.rejects(client.websocket(base + '/reject'))
  await assert.rejects(new Client().websocket(secure + '/echo'))
  client.close()
  console.log('Node WS/WSS, duplex, frames, close handshake, limits and cancellation checks passed')
}
main().catch(error => { console.error(error); process.exitCode = 1 })
