from typing import Any, Awaitable, Mapping, Iterator, AsyncIterator

from .types import (
    Headers, Pairs, FilePath, Platform, HttpVersion,
    TlsOptions as TlsOptions, Http2Options as Http2Options, Identity as Identity,
    MultipartData as MultipartData, MultipartFile as MultipartFile, MultipartPart as MultipartPart,
)

class Error(RuntimeError):
    code: str
    def __init__(self, code: str, message: str) -> None: ...

class Response:
    @property
    def status(self) -> int: ...
    @property
    def http_version(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def headers(self) -> list[tuple[str, bytes]]: ...
    @property
    def body(self) -> bytes: ...
    def text(self, encoding: str = "utf-8", errors: str = "strict") -> str: ...
    def json(self) -> Any: ...
    def raise_for_status(self) -> Response: ...

class StreamResponse:
    @property
    def status(self) -> int: ...
    @property
    def http_version(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def headers(self) -> list[tuple[str, bytes]]: ...
    def raise_for_status(self) -> StreamResponse: ...
    def next_chunk(self) -> bytes | None: ...
    async def next_chunk_async(self) -> bytes | None: ...
    def close(self) -> None: ...
    def __iter__(self) -> Iterator[bytes]: ...
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    def __enter__(self) -> StreamResponse: ...
    def __exit__(self, *args: Any) -> None: ...
    async def __aenter__(self) -> StreamResponse: ...
    async def __aexit__(self, *args: Any) -> None: ...

class WebSocketMessage:
    kind: str
    data: bytes
    code: int | None

class WebSocket:
    protocol: str | None
    def send(self, data: str | bytes) -> None: ...
    def ping(self, data: str | bytes = b"") -> None: ...
    def pong(self, data: str | bytes = b"") -> None: ...
    def recv(self) -> WebSocketMessage | None: ...
    def close(self, code: int = 1000, reason: str = "") -> None: ...
    def abort(self) -> None: ...
    def __iter__(self) -> Iterator[WebSocketMessage]: ...
    def __enter__(self) -> WebSocket: ...
    def __exit__(self, *args: Any) -> None: ...

class AsyncWebSocket:
    protocol: str | None
    async def send(self, data: str | bytes) -> None: ...
    async def ping(self, data: str | bytes = b"") -> None: ...
    async def pong(self, data: str | bytes = b"") -> None: ...
    async def recv(self) -> WebSocketMessage | None: ...
    async def close(self, code: int = 1000, reason: str = "") -> None: ...
    def abort(self) -> None: ...
    def __aiter__(self) -> AsyncIterator[WebSocketMessage]: ...
    async def __aenter__(self) -> AsyncWebSocket: ...
    async def __aexit__(self, *args: Any) -> None: ...

class _BaseClient:
    def __init__(self, timeout_ms: int = 30000, max_response_bytes: int = 16777216, *, connect_timeout_ms: int | None = None, read_timeout_ms: int | None = None, proxy: str | None = None, verify: bool = True, ca_pem: str | None = None, max_redirects: int = 10, cookies: bool = True, user_agent: str | None = None, http_version: HttpVersion = "auto", tls: TlsOptions | None = None, http2: Http2Options | None = None, identity: Identity | None = None, profile: str | None = None, platform: Platform | None = None, decompress: bool = True) -> None: ...
    def clear_cookies(self) -> None: ...
    def set_cookie(self, url: str, value: str) -> None: ...
    def cookies(self, url: str) -> list[tuple[str, str]]: ...
    def close(self) -> None: ...
    def websocket_async(self, url: str, headers: Headers | None = None, *, protocols: list[str] = ..., timeout_ms: int | None = None, operation_timeout_ms: int = 30000, max_message_bytes: int = 16777216) -> Awaitable[AsyncWebSocket]: ...
    def stream_async(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, *, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> Awaitable[StreamResponse]: ...
    def request_async(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, *, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> Awaitable[Response]: ...

class Client(_BaseClient):
    def websocket(self, url: str, headers: Headers | None = None, *, protocols: list[str] = ..., timeout_ms: int | None = None, operation_timeout_ms: int = 30000, max_message_bytes: int = 16777216) -> WebSocket: ...
    def stream(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, *, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> StreamResponse: ...
    def request(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, *, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> Response: ...
    def get(self, url: str, *, headers: Headers | None = None, body: str | bytes | None = None, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> Response: ...
    def post(self, url: str, *, headers: Headers | None = None, body: str | bytes | None = None, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> Response: ...
    def __enter__(self) -> Client: ...
    def __exit__(self, *args: Any) -> None: ...

class AsyncClient(_BaseClient):
    async def websocket(self, url: str, headers: Headers | None = None, *, protocols: list[str] = ..., timeout_ms: int | None = None, operation_timeout_ms: int = 30000, max_message_bytes: int = 16777216) -> AsyncWebSocket: ...
    async def stream(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, *, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> StreamResponse: ...
    async def request(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, *, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> Response: ...
    async def get(self, url: str, *, headers: Headers | None = None, body: str | bytes | None = None, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> Response: ...
    async def post(self, url: str, *, headers: Headers | None = None, body: str | bytes | None = None, params: Pairs | None = None, json: object = ..., form: Pairs | None = None, multipart: list[MultipartPart] | None = None, body_file: FilePath | None = None, basic_auth: tuple[str, str] | None = None, bearer_token: str | None = None, timeout_ms: int | None = None, max_redirects: int | None = None) -> Response: ...
    async def __aenter__(self) -> AsyncClient: ...
    async def __aexit__(self, *args: Any) -> None: ...

def available_profiles() -> list[str]: ...
