from typing import Any, Awaitable, Mapping, Iterator, AsyncIterator

Headers = list[tuple[str, str | bytes]] | Mapping[str, str | bytes]

class Error(RuntimeError):
    code: str
    def __init__(self, code: str, message: str) -> None: ...

class Response:
    @property
    def status(self) -> int: ...
    @property
    def http_version(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def headers(self) -> list[tuple[str, bytes]]: ...
    @property
    def body(self) -> bytes: ...
    def text(self, encoding: str = "utf-8", errors: str = "strict") -> str: ...
    def json(self) -> Any: ...
    def raise_for_status(self) -> Response: ...

class StreamResponse:
    @property
    def status(self) -> int: ...
    @property
    def http_version(self) -> str: ...
    @property
    def url(self) -> str: ...
    @property
    def headers(self) -> list[tuple[str, bytes]]: ...
    def raise_for_status(self) -> StreamResponse: ...
    def next_chunk(self) -> bytes | None: ...
    async def next_chunk_async(self) -> bytes | None: ...
    def close(self) -> None: ...
    def __iter__(self) -> Iterator[bytes]: ...
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    def __enter__(self) -> StreamResponse: ...
    def __exit__(self, *args: Any) -> None: ...
    async def __aenter__(self) -> StreamResponse: ...
    async def __aexit__(self, *args: Any) -> None: ...

class _BaseClient:
    def __init__(self, timeout_ms: int = 30000, max_response_bytes: int = 16777216, *, connect_timeout_ms: int | None = None, read_timeout_ms: int | None = None, proxy: str | None = None, verify: bool = True, ca_pem: str | None = None, max_redirects: int = 10, cookies: bool = True, user_agent: str | None = None, http_version: str = "auto", tls: Mapping[str, Any] | None = None, http2: Mapping[str, Any] | None = None, identity: Mapping[str, str] | None = None, profile: str | None = None, platform: str | None = None, decompress: bool = True) -> None: ...
    def clear_cookies(self) -> None: ...
    def set_cookie(self, url: str, value: str) -> None: ...
    def cookies(self, url: str) -> list[tuple[str, str]]: ...
    def close(self) -> None: ...
    def stream_async(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, **options: Any) -> Awaitable[StreamResponse]: ...
    def request_async(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, **options: Any) -> Awaitable[Response]: ...

class Client(_BaseClient):
    def stream(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, **options: Any) -> StreamResponse: ...
    def request(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, **options: Any) -> Response: ...
    def get(self, url: str, **options: Any) -> Response: ...
    def post(self, url: str, **options: Any) -> Response: ...
    def __enter__(self) -> Client: ...
    def __exit__(self, *args: Any) -> None: ...

class AsyncClient(_BaseClient):
    async def stream(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, **options: Any) -> StreamResponse: ...
    async def request(self, method: str, url: str, headers: Headers | None = None, body: str | bytes | None = None, **options: Any) -> Response: ...
    async def get(self, url: str, **options: Any) -> Response: ...
    async def post(self, url: str, **options: Any) -> Response: ...
    async def __aenter__(self) -> AsyncClient: ...
    async def __aexit__(self, *args: Any) -> None: ...

def available_profiles() -> list[str]: ...
