[package]
name = "tlsurl-node"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
tlsurl-core = { path = "../../crates/tlsurl-core" }
napi = { version = "3", default-features = false, features = ["napi8", "tokio_rt"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"
