/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class Cancellation {
  constructor()
  cancel(): void
}

export declare class Client {
  constructor(timeoutMs?: number | undefined | null, maxResponseBytes?: number | undefined | null, options?: string | undefined | null)
  setCookie(url: string, value: string): void
  cookies(url: string): Array<Cookie>
  clearCookies(): void
  request(method: string, url: string, headers: Array<Header> | undefined | null, body: Buffer | undefined | null, options: string | undefined | null, cancellation: Cancellation): Promise<Response>
  stream(method: string, url: string, headers: Array<Header> | undefined | null, body: Buffer | undefined | null, options: string | undefined | null, cancellation: Cancellation): Promise<StreamResponse>
  websocket(url: string, headers: Array<Header>, options: string, cancellation: Cancellation): Promise<WebSocket>
}

export declare class StreamResponse {
  get status(): number
  get httpVersion(): string
  get url(): string
  get headers(): Array<Header>
  close(): void
  nextChunk(): Promise<Buffer | undefined | null>
}

export declare class WebSocket {
  get protocol(): string | null
  abort(): void
  send(kind: string, data: Buffer): Promise<undefined>
  recv(): Promise<WebSocketMessage | undefined | null>
  close(code: number, reason: string): Promise<undefined>
}

export declare function availableProfiles(): Array<string>

export interface Cookie {
  name: string
  value: string
}

export interface Header {
  name: string
  value: Buffer
}

export interface Response {
  status: number
  httpVersion: string
  url: string
  headers: Array<Header>
  body: Buffer
}

export interface WebSocketMessage {
  kind: string
  data: Buffer
  code?: number
}
