/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class Client {
  constructor(timeoutMs?: number | undefined | null, maxResponseBytes?: number | undefined | null)
  request(method: string, url: string, headers?: Array<Header> | undefined | null, body?: Buffer | undefined | null): Promise<Response>
}

export interface Header {
  name: string
  value: Buffer
}

export interface Response {
  status: number
  url: string
  headers: Array<Header>
  body: Buffer
}
